name: Release to PyPI

on:
  release:
    types:
      - published
    branches:
      - "main"

jobs:
  publish:
    name: Publish Package to PyPI
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools twine
        shell: bash

      - name: Build Package
        run: |
          python setup.py sdist bdist_wheel
        shell: bash

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload --repository pypi dist/*
        shell: bash